/**
 * fix-issue action — STUB for Day 1.
 *
 * The real implementation (Day 2-3) will:
 *   - read repo files via GitHub Contents API
 *   - drive Claude with a tool-use loop (read_file / write_file / run_tests)
 *   - stage changes and push to a fork/branch
 *   - hand off to create-pr
 *
 * For Day 1 we return a mock "fix plan" so the dashboard has a draft payload
 * to render through the review flow.
 */

const { Core } = require('@adobe/aio-sdk')
const { getIssue, putIssue } = require('../common/state')
const { errorResponse, stringParameters } = require('../utils')

async function main (params) {
  const logger = Core.Logger('fix-issue', { level: params.LOG_LEVEL || 'info' })

  try {
    logger.debug(stringParameters(params))

    const { repo, number } = params
    if (!repo || !number) {
      return errorResponse(400, 'repo and number are required', logger)
    }

    const issue = await getIssue(repo, Number(number))
    if (!issue) {
      return errorResponse(404, `Issue ${repo}#${number} not found in state`, logger)
    }

    if (!issue.triage) {
      return errorResponse(400, `Issue ${repo}#${number} has not been triaged yet`, logger)
    }

    if (issue.triage.archetype === 'needs-human') {
      const updated = { ...issue, status: 'skipped', skip_reason: 'needs-human triage' }
      await putIssue(repo, Number(number), updated)
      return { statusCode: 200, body: { repo, number: Number(number), status: 'skipped', reason: 'needs-human' } }
    }

    // Day 1 stub — produce a mock draft
    const mockDraft = {
      branch: `prism/fix-${issue.number}`,
      title: `[PRism] ${issue.title}`,
      summary: `Draft fix for ${repo}#${issue.number}.`,
      files_changed: ['(stub) no files changed yet — Day 1 mock'],
      diff: '// Day 1 stub: real diff will appear here once the Claude Agent loop is wired up.\n',
      body: [
        `## PRism draft for #${issue.number}`,
        '',
        `**Archetype:** ${issue.triage.archetype}`,
        `**Priority:** ${issue.triage.priority}`,
        '',
        issue.triage.rationale || '',
        '',
        '> Generated by AI Week Bot — awaiting human review'
      ].join('\n'),
      generated_at: new Date().toISOString()
    }

    const updated = { ...issue, status: 'pr-drafted', draft: mockDraft }
    await putIssue(repo, Number(number), updated)

    return { statusCode: 200, body: { repo, number: Number(number), draft: mockDraft } }
  } catch (error) {
    logger.error(error)
    return errorResponse(500, `fix-issue error: ${error.message}`, logger)
  }
}

exports.main = main
