/**
 * Shared PR-creation logic, used by both fix-issue (inline, so the whole
 * workflow completes in one action invocation) and create-pr (as a standalone
 * action for manual retries).
 *
 * Takes an issue with a real `draft.edits` payload, pushes a branch, commits
 * the edits, and opens a draft PR on origin. Returns the updated state shape
 * the caller should persist.
 */

const {
  octokit, parseRepo, getDefaultBranch,
  createOrResetBranch, commitEdits, createDraftPR
} = require('./github')

/**
 * @returns {{ pr, status }} object the caller should merge into issue state
 */
async function createPRFromDraft ({ githubToken, issue, logger }) {
  const draft = issue.draft
  if (!draft) throw new Error('Issue has no draft')
  if (draft.stub) {
    // Dep-bump stub or similar — no real PR yet.
    return {
      pr: { state: 'draft', stub: true, created_at: new Date().toISOString() },
      status: 'awaiting-review',
      note: 'stub-only; no real PR created'
    }
  }
  if (!draft.edits || draft.edits.length === 0) {
    throw new Error('Draft has no edits')
  }

  const gh = octokit(githubToken)
  const { owner, repo } = parseRepo(issue.repo)
  const defaultBranch = await getDefaultBranch(gh, owner, repo)
  const branchName = draft.branch || `prism/fix-${issue.number}`

  // Idempotency: before creating a branch + PR, check whether this issue
  // already has an open PR on the same branch. If it does, we should update
  // in place (additive commit) rather than force-resetting the branch and
  // opening a duplicate PR. Missing this check caused duplicate-PR bugs when
  // a user clicked "Fix & draft PR" on a re-triaged issue that already had
  // a PR linked.
  let existingPR = null
  if (issue.pr && issue.pr.number) {
    try {
      const res = await gh.pulls.get({ owner, repo, pull_number: issue.pr.number })
      if (res.data.state === 'open' && res.data.head.ref === branchName) {
        existingPR = res.data
      }
    } catch (e) {
      if (e.status !== 404) throw e
    }
  }
  // Also scan for any other open PR from this branch (in case state is stale)
  if (!existingPR) {
    try {
      const search = await gh.pulls.list({
        owner, repo, head: `${owner}:${branchName}`, state: 'open', per_page: 5
      })
      if (search.data.length > 0) existingPR = search.data[0]
    } catch (_) { /* non-fatal */ }
  }

  if (existingPR) {
    // Update in place: additive commit on the existing branch; keep the PR.
    if (logger) logger.info(`[pr] reusing existing PR #${existingPR.number} on ${branchName} — committing additively`)
    const commit = await commitEdits(
      gh, owner, repo, branchName,
      draft.edits.map(e => ({ path: e.path, content: e.content })),
      `Update fix for #${issue.number}\n\nGenerated by Prism`
    )
    return {
      pr: {
        number: existingPR.number,
        state: existingPR.draft ? 'draft' : 'open',
        url: existingPR.html_url,
        head: existingPR.head.ref,
        base: existingPR.base.ref,
        commit_sha: commit.commitSha,
        created_at: existingPR.created_at
      },
      status: 'awaiting-review',
      note: `reused existing PR #${existingPR.number}`
    }
  }

  // Fresh path: no existing PR on this branch.
  if (logger) logger.info(`[pr] resetting branch ${branchName} on ${owner}/${repo} from ${defaultBranch}`)
  await createOrResetBranch(gh, owner, repo, branchName, defaultBranch)

  if (logger) logger.info(`[pr] committing ${draft.edits.length} file edit(s) to ${branchName}`)
  const commit = await commitEdits(
    gh, owner, repo, branchName,
    draft.edits.map(e => ({ path: e.path, content: e.content })),
    `Fix #${issue.number}: ${issue.title}\n\nGenerated by Prism (AI Week 2026)`
  )

  if (logger) logger.info(`[pr] opening draft PR on ${owner}/${repo} from ${branchName}`)
  const pr = await createDraftPR(gh, owner, repo, {
    title: draft.title,
    body: `${draft.body}\n\nCloses #${issue.number}`,
    head: branchName,
    base: defaultBranch
  })

  return {
    pr: {
      number: pr.number,
      state: pr.draft ? 'draft' : 'open',
      url: pr.html_url,
      head: pr.head.ref,
      base: pr.base.ref,
      commit_sha: commit.commitSha,
      created_at: pr.created_at
    },
    status: 'awaiting-review'
  }
}

module.exports = { createPRFromDraft }
