/**
 * Shared PR-creation logic, used by both fix-issue (inline, so the whole
 * workflow completes in one action invocation) and create-pr (as a standalone
 * action for manual retries).
 *
 * Takes an issue with a real `draft.edits` payload, pushes a branch, commits
 * the edits, and opens a draft PR on origin. Returns the updated state shape
 * the caller should persist.
 */

const {
  octokit, parseRepo, getDefaultBranch,
  createOrResetBranch, commitEdits, createDraftPR
} = require('./github')

/**
 * @returns {{ pr, status }} object the caller should merge into issue state
 */
async function createPRFromDraft ({ githubToken, issue, logger }) {
  const draft = issue.draft
  if (!draft) throw new Error('Issue has no draft')
  if (draft.stub) {
    // Dep-bump stub or similar — no real PR yet.
    return {
      pr: { state: 'draft', stub: true, created_at: new Date().toISOString() },
      status: 'awaiting-review',
      note: 'stub-only; no real PR created'
    }
  }
  if (!draft.edits || draft.edits.length === 0) {
    throw new Error('Draft has no edits')
  }

  const gh = octokit(githubToken)
  const { owner, repo } = parseRepo(issue.repo)
  const defaultBranch = await getDefaultBranch(gh, owner, repo)
  const branchName = draft.branch || `prism/fix-${issue.number}`

  if (logger) logger.info(`[pr] resetting branch ${branchName} on ${owner}/${repo} from ${defaultBranch}`)
  await createOrResetBranch(gh, owner, repo, branchName, defaultBranch)

  if (logger) logger.info(`[pr] committing ${draft.edits.length} file edit(s) to ${branchName}`)
  const commit = await commitEdits(
    gh, owner, repo, branchName,
    draft.edits.map(e => ({ path: e.path, content: e.content })),
    `Fix #${issue.number}: ${issue.title}\n\nGenerated by PRism (AI Week 2026)`
  )

  if (logger) logger.info(`[pr] opening draft PR on ${owner}/${repo} from ${branchName}`)
  const pr = await createDraftPR(gh, owner, repo, {
    title: draft.title,
    body: `${draft.body}\n\nCloses #${issue.number}`,
    head: branchName,
    base: defaultBranch
  })

  return {
    pr: {
      number: pr.number,
      state: pr.draft ? 'draft' : 'open',
      url: pr.html_url,
      head: pr.head.ref,
      base: pr.base.ref,
      commit_sha: commit.commitSha,
      created_at: pr.created_at
    },
    status: 'awaiting-review'
  }
}

module.exports = { createPRFromDraft }
